### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by jgm** [ndmitchell/tagsoup#10] opened 2015-07-07 17:00 UTC
I'm not *sure* this is a bug; maybe it's just a dark corner of the HTML5 parsing algorithm?  But I did find it very surprising.  Can you comment?  Is this really valid HTML?
```
Prelude Text.HTML.TagSoup> parseTags
"<www.boe.es/buscar/act.php?id=BOE-A-1996-8930#a66>"
[TagOpen "www.boe.es" [("buscar",""),("act.php?id","BOE-A-1996-8930#a66")]]
```

**Comment by ousia** [comment] 2015-07-08 20:07
Linking back to jgm/pandoc#2277.

The [W3C Markup Validation Service](https://validator.w3.org/) considers `<www.boe.es/buscar/act.php?id=BOE-A-1996-8930#a66>` invalid because of:

1.  The slash.

    For the current document, the validator interprets strings like `<FOO />` according to legacy rules that break the expectations of most authors and thus cause confusing warnings and error messages from the validator. This interpretation is triggered by HTML 4 documents or other SGML-based HTML documents. To avoid the messages, simply remove the "/" character in such contexts. NB: If you expect `<FOO />` to be interpreted as an XML-compatible "self-closing" tag, then you need to use XHTML or HTML5.

    This warning and related errors may also be caused by an unquoted attribute value containing one or more "/". Example: `<a href=http://w3c.org>W3C</a>`. In such cases, the solution is to put quotation marks around the value.

2.  The hash.

    You have used character data somewhere it is not permitted to appear. Mistakes that can cause this error include:

    -   putting text directly in the body of the document without wrapping it in a container element (such as a `<p>aragraph</p>`), or

    -   forgetting to quote an attribute value (where characters such as "%" and "/" are common, but cannot appear without surrounding quotes), or

    -   using XHTML-style self-closing tags (such as `<meta ... />`) in HTML 4.01 or earlier. To fix, remove the extra slash ('/') character. For more information about the reasons for this, see [Empty elements in SGML, HTML, XML, and XHTML](http://www.cs.tut.fi/~jkorpela/html/empty.html).

**Comment by ndmitchell** [comment] 2015-07-09 19:22
So it's certainly invalid (like much of the web :)), but I'm not sure what HTML5 says about it. Feeding it through Chrome and then scraping it with the web inspector gives me (my usual first-pass external HTML5 check) gives:

    <www.boe.es buscar="" act.php?id="BOE-A-1996-8930#a66">

Which perfectly matches TagSoup, so I'm probably right here, but I'll read through the spec in the next few days to double check.

**Comment by ndmitchell** [comment] 2015-07-09 19:23
Note that in HTML5 there is very little that is actually "invalid", it's all mapped to an approximation of something closeish.

**Comment by jgm** [comment] 2015-07-09 19:50
OK, thanks!

+++ Neil Mitchell [Jul 09 15 12:23 ]:

**Comment by ndmitchell** [comment] 2015-07-09 20:40
Going through the HTML5 lexer spec step-by-step I get the same result as TagSoup. the slightly weird bit is that `/` in a tag name switches you to [self-closing-start-tag-state](http://www.w3.org/TR/html5/syntax.html#self-closing-start-tag-state) which then eats the `/` and goes back to attribute name. Once you have that logic, the rest is not too surprising. If you do turn on warnings in TagSoup you get some warnings about each `/` character:

    $ parseTagsOptions parseOptions{optTagWarning=True} "<www.boe.es/buscar/act.php?id=BOE-A-1996-8930#a66>"
    [TagOpen "www.boe.es" [("buscar",""),("act.php?id","BOE-A-1996-8930#a66")]
    ,TagWarning "Unexpected \"/\""
    ,TagWarning "Unexpected \"/\""]

**Closed** 2015-07-09 20:40 UTC

**Comment by jgm** [comment] 2015-07-09 20:47
Ah, good, maybe if I turn on warnings I can make the
discriminations I need to make.

+++ Neil Mitchell [Jul 09 15 13:40 ]:
